In [1]:
import numpy as npy
i=npy.array([[1,2,3,4],[1,2,3,4]])
k=npy.array([[1,2,3,4]])
j=npy.array([[1,2,3,4],[1,2,3,4]])

In [2]:
npy.dot(i,j.T)

array([[30, 30],
       [30, 30]])

In [3]:
o=npy.array([[1,2]])

In [4]:
one=npy.ones(4)
zero=npy.zeros(4)


In [5]:
npy.arange(4,10).reshape(2,3)

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
u=npy.identity(5)

In [7]:
a = npy.array([[1,2,3,4]])
b = npy.array([1,2,3,4])

In [8]:
a.T*b

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])